### ISSUE TITLE
Internal compiler error: An attempt to get register for unknown Value.

### ISSUE THREAD

**Issue by ewynx** [FuelLabs/sway#4631]
When trying to compile the predicate in this repo https://github.com/hashcloak/fuel-crypto/tree/wallet_predicate/predicate, using `forc 0.40.1` it gives the following error:
```
error: Internal compiler error: An attempt to get register for unknown Value.
Please file an issue on the repository and include the code that triggered this error.
```

The predicate code starts here: https://github.com/hashcloak/fuel-crypto/blob/wallet_predicate/predicate/src/main.sw#L51

If we copy some of the functionality directly in the `main` function (instead of calling them from a library), it's possible to get a little bit further, but then eventually will bump into the error posted in this other issue: https://github.com/FuelLabs/sway/issues/4625

**Comment by vaivaswatha** [comment]
The error reported here should be solved by #4628. However just as with #4511 and #4625 , after the fix, I'm seeing 

```error: Internal compiler error: The allocator cannot resolve a register mapping for this program. This is a temporary artifact of the early stage version of this compiler.  Using #[inline(never)] on some functions may help.
Please file an issue on the repository and include the code that triggered this error.```

I'm going to close this as there are two other tracking the same problem.

**Comment by man2706kum** [comment]
Since https://github.com/FuelLabs/sway/pull/4628 was merged in master, the predicate should get compiled by forc build from source but the error `error: The allocator cannot resolve a register mapping for this program....` is still showing up.
